"""empty message

Revision ID: 50fe3b2c84c9
Revises: 6e10d0ad5159
Create Date: 2025-03-31 22:17:08.017579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fe3b2c84c9'
down_revision = '6e10d0ad5159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fs_uniquifier', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['fs_uniquifier'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('last_login')
        batch_op.drop_column('fs_uniquifier')
        batch_op.drop_column('active')
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
