"""empty message

Revision ID: 71904c5c6ada
Revises: c8f23f7a9834
Create Date: 2025-04-02 12:49:13.395047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71904c5c6ada'
down_revision = 'c8f23f7a9834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['staff_id'])
        batch_op.create_foreign_key(None, 'staffs', ['staff_id'], ['id'])
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('staff_id')

    # ### end Alembic commands ###
