"""empty message

Revision ID: 730ba711f62c
Revises: 882912946af1
Create Date: 2025-04-01 14:28:21.918833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730ba711f62c'
down_revision = '882912946af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('active')

    # ### end Alembic commands ###
