"""empty message

Revision ID: 882912946af1
Revises: dea81190f0f1
Create Date: 2025-04-01 14:12:02.736185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882912946af1'
down_revision = 'dea81190f0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles_users', schema=None) as batch_op:
        batch_op.drop_constraint('roles_users_role_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('roles_users_staff_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'staffs', ['staff_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('roles_users_staff_id_fkey', 'staffs', ['staff_id'], ['id'])
        batch_op.create_foreign_key('roles_users_role_id_fkey', 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###
